### ISSUE TITLE
chic 主题设置搜索栏

### ISSUE THREAD

**Issue by kiga-hub** [tucorrine/tucorrine.github.io#1]
请教一下怎么设置。搜索功能？
参考了网上的资料，完全不能使用

**Comment by tucorrine** [comment]
您好

以下是我之前架搜索框時的紀錄，不知道是否能夠直接幫助您?
https://tucorrine.github.io/2020/12/15/search%20bar/

如果看完還是有疑惑的話，歡迎再詢問 :)

**Comment by kiga-hub** [comment]
> 您好
> 
> 以下是我之前架搜索框時的紀錄，不知道是否能夠直接幫助您?
> https://tucorrine.github.io/2020/12/15/search%20bar/
> 
> 如果看完還是有疑惑的話，歡迎再詢問 :)

非常感谢~   我试试看
